language: python
python: "3.6"
addons:
  postgresql: "9.6"
services: postgresql
before_script:
  - psql -c "CREATE USER chado_user WITH SUPERUSER PASSWORD 'chado_pw';" -U postgres
  - createdb -U postgres -O chado_user chado_user
  - pip install codecov
env:
  - TRAVIS_BUILD=yes
script:
  - coverage run setup.py test
after_success:
  - codecov
